name: Relenv Python Package

on: workflow_call

jobs:
  build:
    name: Publish Python Wheel
    runs-on: ubuntu-latest
    environment: release
    premissions:
      id-token: write
    steps:
      - name: Download Source Tarball Artifact
        uses: actions/download-artifact@v4
        with:
          name: Source Tarball
          path: dist
      - name: Download Wheel Artifact
        uses: actions/download-artifact@v4
        with:
          name: Python Wheel
          path: dist
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.4
        with:
          verbose: true
          print-hash: true
          skip-existing: true
          verify-metadata: true
          #username: dwoz
          #password: ${{ secrets.PYPI_API_TOKEN }}
