name: Deploy Python Package

on:
  workflow_dispatch:
    inputs:
      run_id:
        required: true

jobs:
  build:
    name: Publish Python Wheel
    runs-on: ubuntu-latest
    environment: release
    steps:

      - name: Download Source Tarball Artifact
        uses: actions/download-artifact@v4
        with:
          name: Source Tarball
          path: dist
          run_id: ${{ inputs.run_id }}
          gihtub-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Wheel Artifact
        uses: actions/download-artifact@v4
        with:
          name: Python Wheel
          path: dist
          run_id: ${{ inputs.run_id }}
          gihtub-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
          skip-existing: true
          verify-metadata: true
